name: Node CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [13.6.0]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm ci
    - name: npm build
      run: npm run-script build
    - name: npm lint
      run: npm run-script lint
    - name: npm test
      run: npm run-script test
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./reports/test-coverage/cobertura-coverage.xml
        fail_ci_if_error: true
    - name: npm publish
      shell: bash
      run: ./.github/scripts/publish.sh
      env:
        CI: true
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}